#!/bin/sh

set -e

flatpak remote-add --if-not-exists --system appcenter https://flatpak.elementary.io/repo.flatpakrepo
flatpak install --system -y io.elementary.screenshot//stable

#DEBHELPER#

exit 0
