name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:daily
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: screenshot.flatpak
          manifest-path: io.elementary.screenshot.yml
          run-tests: true
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"

  lint:
    runs-on: ubuntu-latest
    
    container:
      image: valalang/lint
      
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: io.elementary.vala-lint -d .
