name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libcanberra-dev libgranite-dev libgtk-3-dev libgdk-pixbuf2.0-dev libhandy-1-dev meson valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  flatpak:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable
      options: --privileged

    steps:
    - uses: actions/checkout@v1
    - name: Install flatpak-builder
      run: |
        apt update
        apt install -y flatpak flatpak-builder
    - name: Add flathub
      run: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: Build manifest
      run: flatpak-builder --repo=flatpak-repo --force-clean --disable-rofiles-fuse --ccache --install-deps-from=flathub flatpak-build io.elementary.screenshot.yml

  lint:

    runs-on: ubuntu-latest
    
    container:
      image: valalang/lint
      
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .
